### ISSUE TITLE
想请教下思维导图第三次遍历，selfMinY的初始逻辑，为什么是这样写

### ISSUE THREAD

**Issue by Liugq5713** [wanglin2/tree_layout#2]
// 节点自身的最大y值和最小y值
    let selfMinY = tree.y - tree.height / 2
    let selfMaxY = tree.y + tree.height / 2

为啥是加减高度的一半呢

**Comment by wanglin2** [comment]
因为y值是节点的中间位置，那么对于该节点，它的minY不就是节点的最上方吗，就是y-高度的一半
